last-release:
  code_git_repo: paritytech/polkadot-sdk
  code_git_ref: polkadot-stable2603-2
  debian-versions:
    - bookworm
    - trixie
  rust-versions:
    - "1.93.0"
  clang-versions:
    - 21
  rustc-targets:
    - x86-64-v3
  components:
    - polkadot
    - substrate-node
    - polkadot-parachain
    - polkadot-omni-node
stable2512:
  code_git_repo: paritytech/polkadot-sdk
  code_git_ref: polkadot-stable2512-3
  debian-versions:
    - bookworm
    - trixie
  rust-versions:
    - "1.88.0"
  clang-versions:
    - 21
  rustc-targets:
    - x86-64-v3
  components:
    - polkadot
    - substrate-node
    - polkadot-parachain
    - polkadot-omni-node