ARG IMAGE_VERSION

FROM ${IMAGE_VERSION}

ARG GIT_REF

ENV WASM_BUILD_WORKSPACE_HINT="/home/rust/polkadot-sdk"

RUN git clone https://github.com/paritytech/polkadot-sdk.git polkadot-sdk --branch ${GIT_REF} --single-branch
WORKDIR /home/rust/polkadot-sdk
#RUN git checkout
RUN cargo build --profile production --locked --package polkadot --bin polkadot
