ARG IMAGE_VERSION

FROM ${IMAGE_VERSION}

ARG GIT_REPO
ARG GIT_REF

ENV WASM_BUILD_WORKSPACE_HINT="/home/rust/polkadot-sdk"

RUN git clone https://github.com/${GIT_REPO}.git /home/rust/polkadot-sdk --branch ${GIT_REF} --single-branch
WORKDIR /home/rust/polkadot-sdk
RUN cargo build --profile production --locked --bin polkadot --bin polkadot-execute-worker --bin polkadot-prepare-worker
