ARG IMAGE_VERSION

FROM ${IMAGE_VERSION}

ARG GIT_REPO
ARG GIT_REF

ENV WASM_BUILD_WORKSPACE_HINT="/home/rust/polkadot-sdk"

ENV RUSTFLAGS="-C target-cpu=x86-64-v3"
ENV CFLAGS="-pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mpclmul -march=x86-64-v3"
ENV CXXFLAGS="-pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mpclmul -march=x86-64-v3"

RUN git clone https://github.com/${GIT_REPO}.git /home/rust/polkadot-sdk --branch ${GIT_REF} --single-branch
WORKDIR /home/rust/polkadot-sdk
RUN cargo build --profile production --locked --bin polkadot --bin polkadot-execute-worker --bin polkadot-prepare-worker
