ARG DEBIAN_VERSION=bookworm

FROM debian:${DEBIAN_VERSION}-slim

ARG DEBIAN_VERSION=bookworm
ARG RUST_STABLE_VERSION="1.84.1"
ARG CLANG_VERSION="19"

# Set environment variables
ENV SHELL="/bin/bash"
ENV DEBIAN_FRONTEND="noninteractive"

ENV RUSTUP_HOME="/opt/rustup_home"
ENV CARGO_HOME="/opt/cargo_home"
ENV CARGO_TARGET_DIR="/opt/cargo_target"
ENV PATH="$PATH:$CARGO_HOME/bin"

ENV CC="clang-$CLANG_VERSION"
ENV CXX="clang-$CLANG_VERSION"
ENV LD="lld-$CLANG_VERSION"

ENV RUST_BACKTRACE=1

# Install dependencies
RUN set -eux && \
    apt-get -y update && \
    apt-get install --no-install-recommends -y curl ca-certificates apt-transport-https && \
    echo "deb https://deb.debian.org/debian ${DEBIAN_VERSION}-backports main" >> /etc/apt/sources.list.d/${DEBIAN_VERSION}-backports.list && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key -o /etc/apt/keyrings/llvm.asc && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/llvm.asc] https://apt.llvm.org/${DEBIAN_VERSION}/ llvm-toolchain-${DEBIAN_VERSION}-$CLANG_VERSION main" | tee /etc/apt/sources.list.d/llvm-toolchain.list > /dev/null && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian ${DEBIAN_VERSION} stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get -y update && \
    apt-get install --no-install-recommends -y \
        # tools
        git bash sudo nano gh yq \
        # compilers
        clang-$CLANG_VERSION lldb-$CLANG_VERSION lld-$CLANG_VERSION libclang-$CLANG_VERSION-dev make \
        # dependencies
        protobuf-compiler \
        # docker
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang-$CLANG_VERSION 100 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang-$CLANG_VERSION 100 && \
    update-alternatives --install /usr/bin/ld ld /usr/bin/ld.lld-$CLANG_VERSION 100 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-$CLANG_VERSION  100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-$CLANG_VERSION 100 && \
    rm -rf /var/lib/apt/lists/*

RUN useradd rust --create-home -u 1000 --groups sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN mkdir ${RUSTUP_HOME} ${CARGO_HOME} ${CARGO_TARGET_DIR}
run chown -R rust:rust ${RUSTUP_HOME} ${CARGO_HOME} ${CARGO_TARGET_DIR}
USER rust
# Install rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain ${RUST_STABLE_VERSION} && \
    rustup component add rust-src --toolchain ${RUST_STABLE_VERSION}-x86_64-unknown-linux-gnu && \
    rustup target add wasm32v1-none --toolchain ${RUST_STABLE_VERSION}
RUN command -v wasm-gc || \
    cargo +${RUST_STABLE_VERSION} install --git https://github.com/alexcrichton/wasm-gc --force
WORKDIR /home/rust

ENTRYPOINT ["/bin/bash"]
