ARG IMAGE_VERSION

FROM ${IMAGE_VERSION}

ARG GIT_REF

WORKDIR /home/rust
RUN git clone https://github.com/paritytech/polkadot-sdk.git polkadot-sdk && cd polkadot-sdk && git checkout ${GIT_REF}
RUN cd polkadot-sdk/polkadot && cargo build --release