name: main branch

on:
  push:
    branches:
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        debian-versions: [buster, bullseye, bookworm]
        rust-versions: [1.72.0]
        clang-versions: [15]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: echo ${{ github.ref }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles
          file: dockerfiles/Dockerfile.amd64
          push: false
          tags: "${{ env.REGISTRY }}/${{ github.repository }}:debian-${{ matrix.debian-versions }}-rust-${{ matrix.rust-versions }}-clang-${{ matrix.clang-versions }}"
